---
title: "Multilevel Analysis"
author: "Pamela Inostroza"
date: "27/04/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE, warning=FALSE}

knitr::opts_chunk$set(echo = TRUE)
library(psych)
library(expss)
library(sjlabelled)
library(dplyr)
library(reshape)
library(lavaan)
library(lme4)
library(lmerTest)

```

```{r data, include=FALSE,echo=FALSE, warning=FALSE , eval=FALSE}

setwd("C:/Users/pamel/Documents/ESS/")
load("ESS5-9Round.RData")

#Human values from round 4 to 9
# items_o <- c("ipshabt", "ipsuces", "iphlppl", "iplylfr", "ipfrule", "ipbhprp", "ipgdtim", 
#           "impfun", "imprich", "iprspot", "impsafe", "ipstrgv", "ipcrtiv", "impfree", 
#           "impdiff", "ipadvnt", "ipmodst", "imptrad", "ipeqopt", "ipudrst", "impenv") 
# 
#Media and social trust
#items_o <- c("ppltrst","pplfair","pplhlp")
#8 "nwsptot"  "nwsppol"  "netuse"
#9 "nwspol","netusoft","netustm"

#Attitute towards immigration
#items_o <- c("imsmetn","imdfetn","impcntr","imbgeco","imueclt","imwbcnt")

items_o <- c("imsmetn","imdfetn","impcntr","imbgeco","imueclt","imwbcnt","ppltrst","pplfair","pplhlp","ipshabt", 
             "ipsuces", "iphlppl", "iplylfr", "ipfrule", "ipbhprp", "ipgdtim", "impfun", "imprich", "iprspot", 
             "impsafe", "ipstrgv", "ipcrtiv", "impfree", "impdiff", "ipadvnt", "ipmodst", "imptrad", "ipeqopt", 
             "ipudrst", "impenv")

id <- c("essround","idno","cntry", "dweight", "hhmmb", "agea","eduyrs",
          "GINI", "GDP", "HDI")
vars <- c("gndr", "dvrcdeva", "domicil", "eisced")

ds_filtradaAll <- ds[c(items_o,id,vars)]
describe(ds_filtradaAll[,c(id,vars)])

describeBy(ds_filtradaAll[,items_o], ds_filtradaAll$essround, mat = TRUE)

recod3 <- c("ipshabt", "ipsuces", "iphlppl", "iplylfr", "ipfrule", "ipbhprp", "ipgdtim", 
             "impfun", "imprich", "iprspot", "impsafe", "ipstrgv", "ipcrtiv", "impfree", 
             "impdiff", "ipadvnt", "ipmodst", "imptrad", "ipeqopt", "ipudrst", "impenv")
dat3 <- data.frame(reverse.code(keys = rep(-1,length(recod3)), 
                                items = ds_filtradaAll[,recod3], 
                                mini = rep(1,length(recod3)), 
                                maxi = rep(6,length(recod3))))
colnames(dat3) <- paste(recod3,"_r",sep = "")
 

recod32 <- c("imsmetn","imdfetn","impcntr")
dat32 <- data.frame(reverse.code(keys = rep(-1,length(recod32)), 
                                items = ds_filtradaAll[,recod32], 
                                mini = rep(1,length(recod32)), 
                                maxi = rep(4,length(recod32))))
colnames(dat32) <- paste(recod32,"_r",sep = "")
 
ds_filtradaAll <- cbind(ds_filtradaAll, dat3, dat32)

var_lab(ds_filtradaAll$hhmmb) <- "N° people in household"
var_lab(ds_filtradaAll$agea) <- "Age"

ds_filtradaAll$gndrD <- ifelse(ds_filtradaAll$gndr == 1, 0, 
                               ifelse(ds_filtradaAll$gndr == 2, 1,ds_filtradaAll$gndr))
var_lab(ds_filtradaAll$gndrD) <- "Gender (Female)"
use_labels(ds_filtradaAll,table(gndrD,as.character(cntry)))

ds_filtradaAll$dvrcdevaD <- ifelse(ds_filtradaAll$dvrcdeva == 2, 0, 
                               ifelse(ds_filtradaAll$dvrcdeva == 1, 1,ds_filtradaAll$dvrcdeva))
var_lab(ds_filtradaAll$dvrcdevaD) <- "Divorced (Yes)"
use_labels(ds_filtradaAll,table(dvrcdevaD,as.character(cntry)))

ds_filtradaAll$eiscedT <- ifelse(ds_filtradaAll$eisced %in% c(1,2,3) , 1,
                              ifelse(ds_filtradaAll$eisced %in% c(4,5),2,
                                     ifelse(ds_filtradaAll$eisced %in% c(6,7), 3,NA)))
val_lab(ds_filtradaAll$eiscedT) = num_lab("
            1 Less than Upper secondary
            2 Upper secondary or vocational
            3 Bachelor or higher
")
var_lab(ds_filtradaAll$eiscedT) <- "Educational level"
use_labels(ds_filtradaAll,table(eiscedT,as.character(cntry)))
eiscedD <- as.dichotomy(ds_filtradaAll$eiscedT, prefix="eisced")
names(eiscedD)

ds_filtradaAll$domicilT <- ifelse(ds_filtradaAll$domicil %in% c(4,5) , 1,
                                  ifelse(ds_filtradaAll$domicil %in% c(3) , 2,
                                         ifelse(ds_filtradaAll$domicil %in% c(2),3,
                                                ifelse(ds_filtradaAll$domicil %in% c(1),4,NA))))

val_lab(ds_filtradaAll$domicilT) <- num_lab("
             1 Countryside 
             2 Town or small city
             3 Suburbs or outskirts of big city    
             4 A big city
")
var_lab(ds_filtradaAll$domicilT) <- "Domicile"
use_labels(ds_filtradaAll,table(domicilT,as.character(cntry)))
domicilD <- as.dichotomy(ds_filtradaAll$domicilT, prefix="domicil")
names(domicilD)
ds_filtradaAll <- cbind(ds_filtradaAll, eiscedD, domicilD)

exog <- c(items_o[!items_o %in% c(recod3,recod32)],names(dat3), names(dat32))
items <- c(id,exog,"gndrD","dvrcdevaD",names(eiscedD),names(domicilD))

newvars <- c("gndr", "dvrcdeva", "domicilT", "eiscedT")

rm(list = c("dat3","dat32","domicilD","eiscedD","id","vars","items_o","recod3"))
```

# Scores 

```{r cars, echo=FALSE, warning=FALSE, eval=FALSE}

Model <- '
achie =~ ipshabt_r + ipsuces_r
confo =~ ipfrule_r + ipbhprp_r
hedon =~ ipgdtim_r + impfun_r
power =~ imprich_r + iprspot_r
secur =~ impsafe_r + ipstrgv_r
selfd =~ ipcrtiv_r + impfree_r
stimu =~ impdiff_r + ipadvnt_r
tradi =~ ipmodst_r + imptrad_r
Benev =~ iphlppl_r + iplylfr_r
Unive =~ ipeqopt_r + ipudrst_r + impenv_r
Trust =~ ppltrst + pplfair + pplhlp
Rejec =~ imsmetn_r + imdfetn_r + impcntr_r
AtImm =~ imbgeco + imueclt + imwbcnt
'

for (r in c(5,6,7,8,9)) {
  ds_filtrada <- ds_filtradaAll %>% filter(essround == r)

  lavaan.fit3 <- lavaan(Model, data=ds_filtrada, auto.fix.first=TRUE,
                       auto.var=TRUE, int.ov.free=TRUE,
                       auto.cov.lv.x=TRUE,estimator="MLM",
                       cluster = "cntry", meanstructure=TRUE)
  assign(paste0("lavaan.fit3r",r),lavaan.fit3)
  print(paste("Fit measures round:", r))
  print(fitMeasures(lavaan.fit3, c("cfi", "rmsea", "srmr")))
  
  b0 <- data.frame(fitted(lavaan.fit3)$cov)
  b1 <- data.frame(round(cov(ds_filtrada[,exog], use="complete.obs"),3))
  b1 <- b1[names(b0), names(b0)]
  b <- round(b0-b1,1)
  
  print(paste("Covariance difference round:", r))
  print(b)
  
  fit = data.frame(fit = fitted(lavaan.fit3)$mean)
  fit$rowname <- rownames(fit)
  real = data.frame(real = round(colMeans(ds_filtrada[,exog], na.rm = TRUE),6))
  real$rowname <- rownames(real)
  a <- left_join(fit, real, by = "rowname")
  a$dif <- round(a$fit - a$real,1)
  print(paste("Means difference round:", r))
  print(a)
  
  idx <- lavInspect(lavaan.fit3, "case.idx")
  
  fscores <- sapply(data.frame(lavPredict(lavaan.fit3)), 
                    function(x) (x-min(x))/(max(x)-min(x))*100 ) #indicator (min 0 - max 100)
  
  for (fs in colnames(fscores)) {
    ds_filtrada[idx, fs] <- fscores[ , fs]
  }
  assign(paste0("ds_filtrada",r),ds_filtrada)
}

ds_filtradaALLScores <- rbind(ds_filtrada5,ds_filtrada6,ds_filtrada7,ds_filtrada8,ds_filtrada9)

latent <- c("selfd","stimu","hedon","achie","power","secur","confo","tradi","Benev",
            "Unive","Trust","Rejec","AtImm")
ds_filtradaALLScores %>% group_by(cntry) %>% summarise(selfd = mean(selfd, na.rm = TRUE),
                                                       stimu = mean(stimu, na.rm = TRUE),
                                                       hedon = mean(hedon, na.rm = TRUE),
                                                       achie = mean(achie, na.rm = TRUE),
                                                       power = mean(power, na.rm = TRUE),
                                                       secur = mean(secur, na.rm = TRUE),
                                                       confo = mean(confo, na.rm = TRUE),
                                                       tradi = mean(tradi, na.rm = TRUE),
                                                       Benev = mean(Benev, na.rm = TRUE),
                                                       Unive = mean(Unive, na.rm = TRUE),
                                                       Trust = mean(Trust, na.rm = TRUE),
                                                       Rejec = mean(Rejec, na.rm = TRUE),
                                                       AtImm = mean(AtImm, na.rm = TRUE)) 

library(parameters)

ds_filtrada1 <- ds_filtradaALLScores %>% 
  select(cntry,essround,idno, Trust, agea, gndr, eduyrs, Benev, HDI, GDP) %>%
  na.omit() %>%  
  mutate(gr = paste(cntry,essround)) 
df <- ds_filtrada1 %>% 
  cbind(demean(ds_filtrada1, select = c("agea","eduyrs", "Benev","GDP"), group = "gr",
         suffix_demean = "_wcr", suffix_groupmean = "_bcr")) %>% 
  cbind(demean(ds_filtrada1, select = c("agea","eduyrs", "Benev","GDP"), group = "cntry",
         suffix_demean = "_wc", suffix_groupmean = "_bc")) %>% # from package "parameters"
  mutate(cons = 1,
         time = ifelse(essround == 5, 0, ifelse(essround == 6, 1 , ifelse(essround == 7,2, 
                ifelse(essround == 8, 3, ifelse(essround == 9, 4, NA)))))) %>% 
  select(cntry, essround, idno, Trust, agea_wcr, gndr,eduyrs, eduyrs_wcr, eduyrs_bcr, Benev_wcr, GDP_bcr, 
         agea_wc, eduyrs_wc, eduyrs_bc, Benev_wc, GDP_bc, cons,time, gr) %>% 
  filter(!is.na(Trust)) %>% 
  arrange(cntry,essround,idno)

dir1 <- c("G:/My Drive/Master in Statistics/Multilevel analysis/Paper/")

write.csv(df,
          paste0(dir1,"MilWinData.csv"),
          row.names = FALSE)
setwd(dir1)
save(df,file="MLData.RData")
```

# Multilevel modelling

```{r model, echo=TRUE, warning=FALSE}

setwd("G:/My Drive/Master in Statistics/Multilevel analysis/Paper/")
load("MLData.RData")
options(scipen=999)

library(ggplot2)

print("# Trust")
df$gr <- paste(df$cntry,df$essround)
ggplot(data = df, aes(x = eduyrs, y=Trust, group=gr)) +
  geom_point()+
  geom_smooth(method = "lm", se = TRUE, aes(colour = gr)) +
  xlab("Years of education") + ylab("Trust index") +
  theme(legend.position = "none")
ggplot(data = df, aes(x = agea, y=Trust, group=gr)) +
  geom_point()+
  geom_smooth(method = "lm", se = TRUE, aes(colour = gr)) +
  xlab("Age") + ylab("Trust index") +
  theme(legend.position = "none")
ggplot(data = df, aes(x = factor(gndr), y=Trust, group=gr)) +
  geom_point()+
  geom_smooth(method = "lm", se = TRUE, aes(colour = gr)) +
  xlab("Gender") + ylab("Trust index") +
  theme(legend.position = "none")
ggplot(data = df, aes(x = Benev, y=Trust, group=gr)) +
  geom_point()+
  geom_smooth(method = "lm", se = TRUE, aes(colour = gr)) +
  xlab("Benevolence index") + ylab("Trust index") +
  theme(legend.position = "none")
ggplot(data = df, aes(x = eduyrs_between, y=Trust, group=gr)) +
  geom_point()+
  geom_smooth(method = "lm", se = TRUE, aes(colour = gr)) +
  xlab("Years of education") + ylab("Trust index") +
  theme(legend.position = "none")
ggplot(data = df, aes(x = GDP, y=Trust, group=gr)) +
  geom_point()+
  geom_smooth(method = "lm", se = TRUE, aes(colour = gr)) +
  xlab("Age") + ylab("Trust index") +
  theme(legend.position = "none")


#Contextual effect = between-within
#Two-level model, essround and eduyrs_within as fixed and random effect 
modelNulla <- lmer(Trust ~  (1|cntry) , 
                  data=df, REML=FALSE)
summary(modelNulla)
nullvara <- as.data.frame(VarCorr(modelNulla))
colnames(nullvara) <-  c("grp","var1","var2","vcov0","sdcor0")
nullvara %>% mutate(icc0=round(vcov0/sum(vcov0)*100,2)) %>% 
  select(grp,var1,var2,vcov0,sdcor0,icc0)

model0a <- lmer(Trust ~ time + (1 + time|cntry) , 
                  data=df, REML=FALSE)
summary(model0a)
ranova(model0a)

model1a <- lmer(Trust ~ agea_wc + factor(gndr) + eduyrs_wc + Benev_wc + time + 
                  (1 + time | cntry) , 
                  data=df, REML=FALSE)
summary(model1a)

#Within-between specification compositional effect, indirect calculation of contextual effect Bc=Bb-Bw
# model2a <- lmer(Trust ~ agea_wcr + factor(gndr) + eduyrs_wcr + Benev_wcr + 
#                   eduyrs_bcr + GDP_bcr + time + 
#                   (1 + time | cntry) , 
#                   data=df, REML=FALSE)

#Mundlak's specification, direct calculation of contextual effect Bc=Bb
model2a <- lmer(Trust ~ agea_wcr + factor(gndr) + eduyrs + Benev_wcr + 
                  eduyrs_bcr + GDP_bcr + time + 
                  (1 + time | cntry) , 
                  data=df, REML=FALSE)
summary(model2a)
ranova(model2a)
nullvara %>% full_join(as.data.frame(VarCorr(model2a))) %>% 
  mutate(varexp = (vcov0-vcov)/sum(vcov0,na.rm = TRUE)*100) %>% 
    mutate_at(4:8, list(~round(., 2))) 

model3a <- lmer(Trust ~ agea_wc + factor(gndr) + eduyrs_wc + Benev_wc + 
                  eduyrs_bc + GDP_bc + time + 
                  (1 + time + eduyrs_wc | cntry) , 
                  data=df, REML=FALSE)
summary(model3a)
ranova(model3a)
nullvara %>% full_join(as.data.frame(VarCorr(model2a))) %>% 
  mutate(varexp = (vcov0-vcov)/sum(vcov0,na.rm = TRUE)*100) %>% 
    mutate_at(4:8, list(~round(., 2))) 
model4a <- lmer(Trust ~ agea_wc + factor(gndr) + eduyrs_wc + Benev_wc + 
                  eduyrs_bc + GDP_bc + time + 
                  (1 + time | cntry) + 
                  (1 + eduyrs_wc || cntry), 
                  data=df, REML=FALSE)
summary(model4a)
ranova(model4a)
nullvara %>% full_join(as.data.frame(VarCorr(model2a))) %>% 
  mutate(varexp = (vcov0-vcov)/sum(vcov0,na.rm = TRUE)*100) %>% 
    mutate_at(4:8, list(~round(., 2))) 

#Three-level model, ess round as fixed and random effect
modelNullb <- lmer(Trust ~  
                     (1|cntry) + 
                     (1|cntry:essround), 
                  data=df, REML=FALSE)
summary(modelNullb)
nullvarb <- as.data.frame(VarCorr(modelNullb))
colnames(nullvarb) <-  c("grp","var1","var2","vcov0","sdcor0")
  nullvar %>% mutate(icc0=round(vcov0/sum(vcov0)*100,2)) %>% 
  select(grp,var1,var2,vcov0,sdcor0,icc0)
  
model1b <- lmer(Trust ~ agea_wcr + factor(gndr) + eduyrs_wcr + Benev_wcr +  
                 (1 |cntry) + 
                 (1 |cntry:essround), 
                  data=df, REML=FALSE)
summary(model1b)
ranova(model1b)
nullvarb %>% full_join(as.data.frame(VarCorr(model1b))) %>% 
  mutate(varexp = (vcov0-vcov)/sum(vcov0,na.rm = TRUE)*100) %>% 
    mutate_at(4:8, list(~round(., 2)))

#Within-between specification compositional effect, indirect calculation of contextual effect Bc=Bb-Bw
# model2b <- lmer(Trust ~ agea_wcr + factor(gndr) + eduyrs_wcr + Benev_wcr + 
#                   eduyrs_bcr + GDP_bcr +  
#                   (1|cntry) + 
#                   (1|cntry:essround), 
#                   data=df, REML=FALSE)

#Mundlak's specification, direct calculation of contextual effect Bc=Bb
model2b <- lmer(Trust ~ agea_wcr + factor(gndr) + eduyrs + Benev_wcr + 
                  eduyrs_bcr + GDP_bcr +  
                  (1|cntry) + 
                  (1|cntry:essround), 
                  data=df, REML=FALSE)
summary(model2b)
ranova(model2b)
nullvarb %>% full_join(as.data.frame(VarCorr(model2b))) %>% 
  mutate(varexp = (vcov0-vcov)/sum(vcov0,na.rm = TRUE)*100) %>% 
    mutate_at(4:8, list(~round(., 2))) 

model3b <- lmer(Trust ~ agea_wcr + factor(gndr) + eduyrs + Benev_wcr +
                  eduyrs_bcr + GDP_bcr +  
                  (1 + eduyrs_wcr|cntry) + 
                  (1 + eduyrs_wcr|cntry:essround), 
                  data=df, REML=FALSE)
summary(model3b)
ranova(model3b)
nullvarb %>% full_join(as.data.frame(VarCorr(model3b))) %>% 
  mutate(varexp = (vcov0-vcov)/sum(vcov0,na.rm = TRUE)*100) %>% 
    mutate_at(4:8, list(~round(., 2))) 

model4b <- lmer(Trust ~ agea_wcr + factor(gndr) + eduyrs + Benev_wcr +
                  eduyrs_bcr + GDP_bcr +  
                  (1 + eduyrs_wcr||cntry) + 
                  (1 + eduyrs_wcr|cntry:essround), 
                  data=df, REML=FALSE)
summary(model4b)
ranova(model4b)
nullvarb %>% full_join(as.data.frame(VarCorr(model4b))) %>% 
  mutate(varexp = (vcov0-vcov)/sum(vcov0,na.rm = TRUE)*100) %>% 
    mutate_at(4:8, list(~round(., 2))) 

df$Fit0 <- predict(modelNull)
anova(model1a,model2a,model3a)
anova(model1b,model2b,model3b)

library(ggplot2)
ggplot(data = df, aes(x = agea, y=Trust, group=gr)) +
  geom_point()+
  geom_smooth(method = "lm", se = TRUE, aes(colour = gr)) +
 # facet_wrap(cntry ~ .) +
  xlab("Age") + ylab("Trust prediction") +
  theme(legend.position = "none")
ggplot(data = ds_filtrada2, aes(x = Benev, y=FitGood, group=cntry)) +
  geom_point()+
  geom_smooth(method = "lm", se = TRUE, aes(colour = cntry)) +
 # facet_wrap(cntry ~ .) +
  xlab("Benevolence index") + ylab("Trust prediction") +
  theme(legend.position = "none")
ggplot(data = ds_filtrada2, aes(x = eduyrs, y=FitGood, group=cntry)) +
  geom_point()+
  geom_smooth(method = "lm", se = TRUE, aes(colour = cntry)) +
 # facet_wrap(cntry ~ .) +
  xlab("Years of education") + ylab("Trust prediction") +
  theme(legend.position = "none")
ggplot(data = ds_filtrada2, aes(x = CntryEduyrs, y=FitGood, group=cntry)) +
  geom_point()+
  geom_smooth(method = "lm", se = TRUE, aes(colour = cntry)) +
 # facet_wrap(cntry ~ .) +
  xlab("Country's Years of education") + ylab("Trust prediction") +
  theme(legend.position = "none")
ggplot(data = ds_filtrada2, aes(x = GDP, y=FitGood, group=cntry)) +
  geom_point()+
  geom_smooth(method = "lm", se = TRUE, aes(colour = cntry)) +
 # facet_wrap(cntry ~ .) +
  xlab("Country's GDP") + ylab("Trust prediction") +
  theme(legend.position = "none")

```
